[package]
name = "Linux-Dashboard"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.33.1"
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
lipsum = "0.9.1"
chrono = "0.4.41"